version: "3.9"

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - ./sessions.json:/app/sessions.json
    restart: unless-stopped

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: weather_bot
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  # "MongoWeiver" — веб-просмотрщик данных (используем mongo-express)
  mongoweiver:
    image: mongo-express:1.0.2-20
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  mongo_data:
